-- ROLES
INSERT INTO roles (NOMBRE) VALUES("ADMIN");
INSERT INTO roles (NOMBRE) VALUES("USUARIO");
INSERT INTO roles (NOMBRE) VALUES("EMPLEADO");
-- PERMISOS
INSERT INTO permisos (NOMBRE) VALUES("CREAR USUARIO");
INSERT INTO permisos (NOMBRE) VALUES("ACTUALIZAR USUARIO");
INSERT INTO permisos (NOMBRE) VALUES("ELIMINAR USUARIO");
INSERT INTO permisos (NOMBRE) VALUES("BUSCAR USUARIO");
INSERT INTO permisos (NOMBRE) VALUES("VER SERVICIOS");
INSERT INTO permisos (NOMBRE) VALUES("EDITAR SERVICIO");
INSERT INTO permisos (NOMBRE) VALUES("ELIMINAR SERVICIO");
INSERT INTO permisos (NOMBRE) VALUES("AGREGAR SERVICIO");
INSERT INTO permisos (NOMBRE) VALUES("COMPRAR SERVICIO");

INSERT INTO roles_permisos(PERMISO_ID,ROL_ID) VALUES(1,1);
INSERT INTO roles_permisos(PERMISO_ID,ROL_ID) VALUES(2,1);
INSERT INTO roles_permisos(PERMISO_ID,ROL_ID) VALUES(3,1);
INSERT INTO roles_permisos(PERMISO_ID,ROL_ID) VALUES(4,1);
INSERT INTO roles_permisos(PERMISO_ID,ROL_ID) VALUES(5,1);

INSERT INTO roles_permisos(PERMISO_ID,ROL_ID) VALUES(2,2);


